Partner analytics
chaynHQ/bloom-frontend pull request #282
Opened 2022-06-05 08:22 UTC by eleanorreem

- Fix jest testing
- ensure partners are coming through in analytics

2022-06-07 16:15 UTC, swetha-charles requested changes
Left a couple of comments - let me know what you think

2022-06-07 16:15 UTC, swetha-charles commented on utils/formatPartnerAccesses.ts
> +  const partnerAdminName = partnerAdmin?.partner?.name;
What do you think about the following (for line 13 onwards)? The set gets rid of the duplication. Let me know if you don't think it's easy to follow. 

```const allPartners = new Set<string>(); // use set to remove duplication between admin and regular partner names
  if (partnerAdminName) allPartners.add(partnerAdminName);
  if (partnerAccessNames) partnerAccessNames.forEach((partner) => allPartners.add(partner));

  return allPartners.size > 0 ? Array.from(allPartners).sort().join(', ') : null;
```

2022-06-07 16:15 UTC, swetha-charles commented on utils/logEvent.ts
> +    partner: joinedPartners(data.partnerAccesses, data.partnerAdmin),
Nice 👍

2022-06-07 16:15 UTC, swetha-charles commented on pages/account/apply-a-code.tsx
> -  }, []);
Following on from what we talked about in the meeting, this is a [link](https://stackoverflow.com/questions/58579426/in-useeffect-whats-the-difference-between-providing-no-dependency-array-and-an) explaining the difference between not giving a dependency array and giving an empty one. 

Thinking about it, I feel like we should include `user` and `partnerAccesses` in the dependency array when the useEffect hook makes use of the two variables. This will make sure the function is only called:
1. on the first render when the component mounts 
2. any time the user or the user's partner access changes. 

I feel like for both of those situations, it makes sense for say google analytics (GA) to get an event. It doesn't really make sense for GA to get an event on each render. 

Let me know if you want to chat through this :)

2022-06-07 17:14 UTC, eleanorreem commented on utils/formatPartnerAccesses.ts
> +  const partnerAdminName = partnerAdmin?.partner?.name;
Yup, I could definitely make it more efficient. However, I'm not a fan of using mutative methods. I will rewrite in a non-mutative way if that's okay?

2022-06-07 17:37 UTC, swetha-charles commented on utils/formatPartnerAccesses.ts
> +  const partnerAdminName = partnerAdmin?.partner?.name;
I don't understand what mutative means in this context - but def go for it if you feel it would be better. Maybe you can explain the mutative bit to me after?

2022-06-07 22:01 UTC, swetha-charles commented on pages/account/apply-a-code.tsx
> -  }, []);
Yeah happy to go for an empty array.

I was thinking we might want to get a log if a user's partner relationships are updated but that will be quite rare.

2022-06-07 22:02 UTC, swetha-charles commented on utils/formatPartnerAccesses.ts
> +  const partnerAdminName = partnerAdmin?.partner?.name;
Thanks for the link.

What do you think about using a set so we don't have to do the unique check?

```  const allPartners = new Set<string>([
    ...(partnerAdminName ? [partnerAdminName] : []),
    ...(partnerAccessNames ? partnerAccessNames : []),
  ]);

  return allPartners.size > 0 ? Array.from(allPartners).sort().join(', ') : null;```

2022-06-08 09:39 UTC, eleanorreem commented on utils/formatPartnerAccesses.ts
> +  const partnerAdminName = partnerAdmin?.partner?.name;
So I looked into making it a set, however, a set is not an ordered data structure. You can't sort it, unfortunately. I think sorting is important here. It means we wont have "Badoo, Bumble" and "Bumble, Badoo" in analytics, we will just have the former.

2022-06-08 09:44 UTC, merged