[] Add custom server to do http to https redirect
chaynHQ/bloom-frontend pull request #337
Opened 2022-07-29 09:17 UTC by eleanorreem

I loosely followed these two guides 
[https://levelup.gitconnected.com/set-up-next-js-with-a-custom-express-server-typescript-9096d819da1c](https://levelup.gitconnected.com/set-up-next-js-with-a-custom-express-server-typescript-9096d819da1c)

[https://stackoverflow.com/questions/66458059/how-do-i-force-or-redirect-my-next-js-website-to-use-https](https://stackoverflow.com/questions/66458059/how-do-i-force-or-redirect-my-next-js-website-to-use-https)

I chose to copy code from heroku ssl redirect because it was such a tiny bit of code, I think its better to maintain it ourselves. Also the npm module uses NODE_ENV as their environment variable setter and we use NEXT_PUBLIC_ENV. I didn't want to change how we use that env variable just for this piece of work. 

Note this wont work for local development

2022-08-04 12:25 UTC, swetha-charles requested changes
Left a slack message as well - let me know what you think.

2022-08-04 12:25 UTC, swetha-charles commented on server/sslRedirect.ts
> +  const isCurrentEnv = environments.includes(currentEnv as unknown as ENVIRONMENT);
Could try [this](https://stackoverflow.com/questions/43804805/check-if-value-exists-in-enum-in-typescript) to avoid the cast. Not 100% sure it'll work.

2022-08-04 12:25 UTC, swetha-charles commented on server/sslRedirect.ts
> +    if (isCurrentEnv) {
Potentially reduce nesting to make it easier to follow:
``` 
return (req: Request, res: Response, next: NextFunction) => {
      if (isCurrentEnv && req.headers['x-forwarded-proto'] !== 'https') {
          res.redirect(status, 'https://' + req.hostname + req.originalUrl);
       } 
      next();
 }
```

2022-08-05 08:12 UTC, eleanorreem commented
I couldn't remember initially why I went for a custom server but I think it was because next middleware is introduced in Next 12.  We are on next 11. It could be worth an upgrade and then we could just use middleware which would look like this






`
import { NextFetchEvent, NextRequest, NextResponse } from 'next/server';

enum Environment {
  PRODUCTION = 'production',
  LOCAL = 'local',
  STAGING = 'staging',
}

type Params = {
  environments?: Environment[];
  status?: 301 | 302;
};

const sslRedirect =
  ({ environments = [Environment.PRODUCTION], status = 301 }: Params) =>
  (req: NextRequest, ev: NextFetchEvent) => {
    const currentEnv = process.env.NEXT_PUBLIC_ENV as Environment;

    if (environments.includes(currentEnv) && req.headers.get('x-forwarded-proto') !== 'https') {
      const hostname = req.headers.get('host') || req.nextUrl.hostname;
      return NextResponse.redirect(`https://${hostname}${req.nextUrl.pathname}`, status);
    }
    return NextResponse.next();
  };

export default sslRedirect({
  environments: [Environment.LOCAL, Environment.STAGING, Environment.PRODUCTION],
});
`
I agree it is alot nicer than rewriting with an express server
I am wondering whether a next upgrade is a good idea anyway because alot of the packages are outdated
I'm happy to hold on this PR and if we prioritise Next upgrade to bring in middleware
Also app.use() is the express way of doing middleware but the only way of getting the middleware into the next app was to create a custom server. Does that make sense?

2022-08-23 22:28 UTC, swetha-charles commented
@eleanorreem Shall we close this PR for now? I assume we'll use the middleware solution as Next is now upgraded.

2022-08-23 22:28 UTC, closed without merging