WIP - Redirect loggedin user
chaynHQ/bloom-frontend pull request #452
Opened 2023-01-06 17:10 UTC by PatriciaRosalis

**TASK**:
- if a user goes to /auth/login, check they are logged in.
- if they are logged in redirect them to the /courses page.

**NOTES**: 
- I think the /auth/login is a public path so it doesn't allow a guard. 
- New behavior with these changes: The user is going to see the login page for 1 sec and then will be redirected to the courses.

2023-01-08 12:52 UTC, eleanorreem commented
Hi Rosalia, Thank you so much for your PR. Your solution works well.
I would suggest one improvement - copy the code snippet you wrote in the NavigationMenu file in /pages/auth/login.tsx. Navigation Menu loads on every page and this snippet isn't necessarily relevant to every page. If you put it in  /pages/auth/login.tsx, it would only run on the /auth/login page and you could remove the later part of your if statement checking the url. I hope that makes sense. Let me know if you have any questions!

2023-01-08 20:36 UTC, swetha-charles requested changes

2023-01-08 20:36 UTC, swetha-charles commented on components/layout/NavigationMenu.tsx
> +  }, [partnerAccesses, t, user, partnerAdmin, router]);
Thanks so much for the PR! 

Echoing what @eleanorreem said, you could add a useEffect in the Login page with the same code snippet. 

We only want to run the effect when the user changes, so just having the user in the dependency array would be better. The router might change for other reasons - we don't necessarily need to run the effect if that happens.  

Let me know if that makes sense :)

2023-01-19 14:09 UTC, PatriciaRosalis commented on components/layout/NavigationMenu.tsx
> +  }, [partnerAccesses, t, user, partnerAdmin, router]);
Totally makes sense! Deleted the router dependency :)

2023-01-25 19:04 UTC, PatriciaRosalis commented
Thanks, @eleanorreem !! What a great review! 😸

2023-01-26 11:34 UTC, swetha-charles approved these changes

2023-01-26 11:34 UTC, merged